/**
 * Created by snatvb on 18.12.16.
 */

export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export const FETCH_USERS_REJECT = 'FETCH_USERS_REJECT';